src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Column(type: "string", nullable: true)]
    private $password;

    #[ORM\Column(type: Types::JSON)]
    private array $roles = [];


    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $telephone = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $datedenaissance = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $profession = null;

    #[ORM\Column]
    private ?bool $client = null;

    #[ORM\Column(nullable: true)]
    private ?int $recommandation_id = null;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'users')]
    #[ORM\JoinColumn(name: "recommandation_id", referencedColumnName: "id")]
    private ?self $recommandation = null;

    #[ORM\OneToMany(mappedBy: 'recommandation', targetEntity: self::class)]
    private Collection $users;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $commentaire = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $contratsSouscrits = null;

    #[ORM\Column(nullable: true)]
    private ?int $Enfants = null;

    #[ORM\Column(length: 255)]
    private ?string $Civil = null;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getDatedenaissance(): ?\DateTimeInterface
    {
        return $this->datedenaissance;
    }

    public function setDatedenaissance(\DateTimeInterface $datedenaissance): self
    {
        $this->datedenaissance = $datedenaissance;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getProfession(): ?string
    {
        return $this->profession;
    }

    public function setProfession(string $profession): self
    {
        $this->profession = $profession;

        return $this;
    }

    public function isClient(): ?bool
    {
        return $this->client;
    }

    public function setClient(bool $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getRecommandation(): ?self
    {
        return $this->recommandation;
    }

    public function setRecommandation(?self $recommandation): self
    {
        $this->recommandation = $recommandation;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(self $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->setRecommandation($this);
        }

        return $this;
    }

    public function removeUser(self $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getRecommandation() === $this) {
                $user->setRecommandation(null);
            }
        }

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getContratsSouscrits(): ?string
    {
        return $this->contratsSouscrits;
    }

    public function setContratsSouscrits(?string $contratsSouscrits): self
    {
        $this->contratsSouscrits = $contratsSouscrits;

        return $this;
    }

    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function getRoles(): array
    {
        $roles = $this->roles ?? [];
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        if ($roles === null) {
            $this->roles = [];
        } else {
            $this->roles = $roles;
        }

        return $this;
    }

    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
    }

    public function __toString(): string
    {
        return $this->getNom() . ' ' . $this->getPrenom();
    }

    public function getEnfants(): ?int
    {
        return $this->Enfants;
    }

    public function setEnfants(?int $Enfants): self
    {
        $this->Enfants = $Enfants;

        return $this;
    }

    public function getCivil(): ?string
    {
        return $this->Civil;
    }

    public function setCivil(string $Civil): self
    {
        $this->Civil = $Civil;

        return $this;
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;

class ClientController extends AbstractController
{
    #[Route('/clients', name: 'app_clients')]
    public function index(Request $request, EntityManagerInterface $entityManager): Response
    {
        $filter = $request->query->get('filter', 'all');
        $search = $request->query->get('search', '');

        // Créer un QueryBuilder
        $queryBuilder = $entityManager->getRepository(User::class)->createQueryBuilder('u');
        
        // Appliquer le filtre de type (client/prospect)
        if ($filter === 'clients') {
            $queryBuilder->andWhere('u.client = :client')
                ->setParameter('client', true);
        } elseif ($filter === 'prospects') {
            $queryBuilder->andWhere('u.client = :client')
                ->setParameter('client', false);
        }
        
        // Appliquer la recherche si un terme est fourni
        if (!empty($search)) {
            $queryBuilder->andWhere('u.nom LIKE :search OR u.prenom LIKE :search OR u.email LIKE :search OR u.profession LIKE :search OR u.adresse LIKE :search OR u.telephone LIKE :search')
                ->setParameter('search', '%' . $search . '%');
        }
        
        // Exécuter la requête
        $clients = $queryBuilder->getQuery()->getResult();

        return $this->render('client/index.html.twig', [
            'clients' => $clients,
            'filter' => $filter,
            'search' => $search,
        ]);
    }
}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Clients{% endblock %}

{% block body %}
<div class="container mt-4">
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
        <a class="navbar-brand" href="{{ path('app_clients') }}">Mon CRM</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if app.user %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('admin') }}">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_logout') }}">Déconnexion</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('app_login') }}">Connexion</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="filter-form">
        <form method="get" action="{{ path('app_clients') }}">
            <div class="form-check">
                <input class="form-check-input" type="radio" name="filter" id="filterAll" value="all" {% if filter == 'all' %}checked{% endif %}>
                <label class="form-check-label" for="filterAll">
                    Tous
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="filter" id="filterClients" value="clients" {% if filter == 'clients' %}checked{% endif %}>
                <label class="form-check-label" for="filterClients">
                    Clients
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="radio" name="filter" id="filterProspects" value="prospects" {% if filter == 'prospects' %}checked{% endif %}>
                <label class="form-check-label" for="filterProspects">
                    Prospects
                </label>
            </div>
            <button type="submit" class="btn btn-primary">Filtrer</button>
        </form>
    </div>

    <div class="search-form mb-4 mt-3">
        <form method="get" action="{{ path('app_clients') }}" class="form-inline">
            <div class="input-group w-100">
                <input type="text" name="search" class="form-control" placeholder="Rechercher un client..." 
                    value="{{ app.request.query.get('search') }}">
                <input type="hidden" name="filter" value="{{ filter }}">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="submit">
                        <i class="fas fa-search"></i> Rechercher
                    </button>
                </div>
            </div>
        </form>
    </div>

    {% if clients|length == 0 %}
    <div class="alert alert-info text-center mt-4">
        Aucun résultat ne correspond à votre recherche.
    </div>
    {% endif %}

    <div class="row justify-content-center">
        <div class="col-12">
            <div class="row">
                {% for client in clients %}
                    <div class="col-md-4">
                        <div class="card mb-4 {% if client.client %}client{% else %}prospect{% endif %}">
                            <div class="card-body">
                                <h5 class="card-title">{{ client.nom }} {{ client.prenom }}</h5>
                                <p class="card-text"><strong>Téléphone:</strong> {{ client.telephone }}</p>
                                <p class="card-text"><strong>Date de naissance:</strong> {{ client.datedenaissance|date('d/m/Y') }}</p>
                                <p class="card-text"><strong>Email:</strong> {{ client.email }}</p>
                                <p class="card-text"><strong>Adresse:</strong> {{ client.adresse }}</p>
                                <p class="card-text"><strong>Profession:</strong> {{ client.profession }}</p>
                                <p class="card-text"><strong>Statut:</strong> {{ client.client ? 'Client' : 'Prospect' }}</p>
                                <p class="card-text"><strong>Recommandé par:</strong> {{ client.recommandation ? client.recommandation.nom ~ ' ' ~ client.recommandation.prenom : 'Aucune' }}</p>
                                <p class="card-text"><strong>Commentaire:</strong> {{ client.commentaire }}</p>
                                <p class="card-text"><strong>Enfants:</strong> {{ client.enfants }}</p>
                                <p class="card-text"><strong>État civil:</strong> {{ client.civil ? client.civil : 'N/A' }}</p>
                                {% if client.client and client.contratsSouscrits %}
                                    <div class="card-text">
                                        <strong>Contrats souscrits:</strong>
                                        <ul class="list-unstyled mt-1">
                                            {% for contrat in client.contratsSouscrits|split('\n') %}
                                                {% if contrat|trim %}
                                                    <li>{{ contrat|trim|replace({'-': '•'}) }}</li>
                                                {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                {% endif %}
                                <a href="tel:{{ client.telephone }}" class="btn btn-primary">Contacter</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}